# Generated by Django 5.2.3 on 2025-08-22 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_tratamento_de_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro_de_tratamento_de_evento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Tratamento de Evento', 'verbose_name_plural': 'Tratamentos de Eventos'},
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='procedimento',
            field=models.TextField(default='Procedimento padrão', verbose_name='Procedimento de Tratamento'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='responsavel',
            field=models.CharField(default='Responsável não definido', max_length=100, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='tempo_estimado',
            field=models.CharField(default='Não definido', max_length=50, verbose_name='Tempo Estimado'),
        ),
        migrations.AddField(
            model_name='cadastro_de_tratamento_de_evento',
            name='tipo_evento',
            field=models.CharField(choices=[('Emergência', 'Emergência'), ('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Baixa Prioridade', 'Baixa Prioridade')], default='Normal', max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='cadastro_de_tratamento_de_evento',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
    ]
