# Generated by Django 5.2.3 on 2025-08-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_tratamento_de_evento', '0002_alter_cadastro_de_tratamento_de_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_de_tratamento_de_evento',
            name='procedimento',
            field=models.TextField(verbose_name='Procedimento de Tratamento'),
        ),
        migrations.AlterField(
            model_name='cadastro_de_tratamento_de_evento',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='cadastro_de_tratamento_de_evento',
            name='tempo_estimado',
            field=models.CharField(max_length=50, verbose_name='Tempo Estimado'),
        ),
        migrations.AlterField(
            model_name='cadastro_de_tratamento_de_evento',
            name='tipo_evento',
            field=models.CharField(choices=[('Emergência', 'Emergência'), ('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Baixa Prioridade', 'Baixa Prioridade')], max_length=50, verbose_name='Tipo de Evento'),
        ),
    ]
