# Generated by Django 5.2.5 on 2025-08-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('nivel_de_importancia', models.CharField(max_length=250)),
                ('acao_a_realizar', models.CharField(max_length=250)),
                ('processo_administrativo', models.BooleanField(default=False)),
            ],
        ),
    ]
