# Generated by Django 5.2.3 on 2025-08-22 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_tipo_nao_conformidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Tipo de Não Conformidade', 'verbose_name_plural': 'Tipos de Não Conformidade'},
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='acao_a_realizar',
            field=models.CharField(max_length=250, verbose_name='Ação a Realizar'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nivel_de_importancia',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=250, verbose_name='Nível de Importância'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='processo_administrativo',
            field=models.BooleanField(default=False, verbose_name='Processo Administrativo'),
        ),
    ]
