# Generated by Django 5.2.5 on 2025-08-26 12:41

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaIscas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estoque_minimo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lote_de', models.CharField(max_length=50)),
                ('lote_ate', models.CharField(max_length=50)),
                ('data_inicio_lancamento', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_iscas', to='entrada_de_iscas.cliente')),
            ],
        ),
    ]
