# Generated by Django 5.2.3 on 2025-08-26 13:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_de_iscas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='entradaiscas',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Entrada de Iscas', 'verbose_name_plural': 'Entradas de Iscas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='entradaiscas',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='entradaiscas',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_iscas', to='entrada_de_iscas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='data_inicio_lancamento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Início Lançamento'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='estoque_minimo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='lote_ate',
            field=models.CharField(max_length=50, verbose_name='Lote (Até)'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='lote_de',
            field=models.CharField(max_length=50, verbose_name='Lote (De)'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
    ]
