# Generated by Django 5.2.5 on 2025-08-26 14:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_de_iscas', '0002_alter_cliente_options_alter_entradaiscas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entradaiscas',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='entradaiscas',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='entradaiscas',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_iscas', to='entrada_de_iscas.cliente'),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='data_inicio_lancamento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='estoque_minimo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='lote_ate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='lote_de',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entradaiscas',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
