# Generated by Django 5.2.5 on 2025-08-28 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('AJ', 'Ajudante')], db_index=True, default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='ATIVO', max_length=8)),
                ('nome', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('rg', models.CharField(max_length=20)),
                ('orgao_emissor_rg', models.CharField(max_length=50)),
                ('estado_emissor_rg', models.CharField(max_length=2)),
                ('data_emissao_rg', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Informe 11 dígitos numéricos para o CPF.')])),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=10)),
                ('naturalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome_pai', models.CharField(max_length=200)),
                ('nome_mae', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('DIVORCIADO', 'DIVORCIADO'), ('VIÚVO', 'VIÚVO')], max_length=15)),
                ('profissao', models.CharField(choices=[('MOTORISTA', 'MOTORISTA'), ('AJUDANTE', 'AJUDANTE'), ('MOTORISTA FOLGUISTA', 'MOTORISTA FOLGUISTA'), ('OP DE REFRIGERA', 'OP DE REFRIGERA'), ('AJUDANTE DE CARGA E DESCARGA', 'AJUDANTE DE CARGA E DESCARGA'), ('AUXILIAR ADM PLENO', 'AUXILIAR ADM PLENO')], max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='pessoa_fisi_nome_de6f25_idx'), models.Index(fields=['cpf'], name='pessoa_fisi_cpf_dd3391_idx'), models.Index(fields=['status'], name='pessoa_fisi_status_5de3b5_idx'), models.Index(fields=['tipo_pessoa'], name='pessoa_fisi_tipo_pe_5d2b6e_idx')],
            },
        ),
    ]
