# Generated by Django 5.2.5 on 2025-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('tipo_de_estacao_de_rastreamento', models.CharField(choices=[('Acompanhamento de Gerenci. de Risco e Logistica', 'Acompanhamento de Gerenci. de Risco e Logisticaônix'), ('Acompanhamento de Gerenciamento de Risco', 'Acompanhamento de Gerenciamento de Risco'), ('Acompanhamento de Logistica', 'Acompanhamento de Logistica')], max_length=50)),
                ('Separacao_de_rastreamento', models.CharField(choices=[('Separado por embarcador transportador', 'Separado por embarcador transportador'), ('Separado por Grau de Rsico', 'Separado por Grau de Rsico'), ('Separado por Tecnologia', 'Separado por Tecnologia'), ('Separado por tipo Manual', 'Separado por Tipo Manual'), ('Separado por tipo de operação', 'Separado por tipo de operação')], max_length=50)),
                ('Numero_maximo_de_veiculos_da_estacao', models.IntegerField()),
                ('Eventos_sem_tratamento', models.BooleanField(default=False)),
                ('Mostrar_no_monitor_de_operacoes', models.BooleanField(default=False)),
                ('Estacao_de_alto_risco', models.BooleanField(default=False)),
                ('Usar_importancia_do_evento_para_redirecionar', models.BooleanField(default=False)),
            ],
        ),
    ]
