# Generated by Django 5.2.3 on 2025-08-22 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao_rastreamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacaorastreamento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Estação de Rastreamento', 'verbose_name_plural': 'Estações de Rastreamento'},
        ),
        migrations.AddField(
            model_name='estacaorastreamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='estacaorastreamento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Estacao_de_alto_risco',
            field=models.BooleanField(default=False, verbose_name='Estação de Alto Risco'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Eventos_sem_tratamento',
            field=models.BooleanField(default=False, verbose_name='Eventos sem Tratamento'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Mostrar_no_monitor_de_operacoes',
            field=models.BooleanField(default=False, verbose_name='Mostrar no Monitor de Operações'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Numero_maximo_de_veiculos_da_estacao',
            field=models.IntegerField(verbose_name='Nº Máximo de Veículos da Estação'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Separacao_de_rastreamento',
            field=models.CharField(choices=[('Separado por embarcador transportador', 'Separado por embarcador transportador'), ('Separado por Grau de Rsico', 'Separado por Grau de Rsico'), ('Separado por Tecnologia', 'Separado por Tecnologia'), ('Separado por tipo Manual', 'Separado por Tipo Manual'), ('Separado por tipo de operação', 'Separado por tipo de operação')], max_length=50, verbose_name='Separação de Rastreamento'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='Usar_importancia_do_evento_para_redirecionar',
            field=models.BooleanField(default=False, verbose_name='Usar Importância do Evento para Redirecionar'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='estacaorastreamento',
            name='tipo_de_estacao_de_rastreamento',
            field=models.CharField(choices=[('Acompanhamento de Gerenci. de Risco e Logistica', 'Acompanhamento de Gerenci. de Risco e Logistica'), ('Acompanhamento de Gerenciamento de Risco', 'Acompanhamento de Gerenciamento de Risco'), ('Acompanhamento de Logistica', 'Acompanhamento de Logistica')], max_length=50, verbose_name='Tipo de Estação de Rastreamento'),
        ),
    ]
