# Generated by Django 5.2.5 on 2025-09-02 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilitarioCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{7}$', 'Informe 7 caracteres (placa).')])),
                ('modelo', models.CharField(max_length=60)),
                ('tipo_carroceria', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('BAU', 'Baú'), ('REFRIGERADA', 'Refrigerada'), ('OUTRA', 'Outra')], max_length=20)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=25)),
                ('ano_fabricacao', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('capacidade_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade (kg)')),
                ('proprietario', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilitário de Carga',
                'verbose_name_plural': 'Utilitários de Carga',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='utilitario__placa_eec3e6_idx'), models.Index(fields=['status'], name='utilitario__status_b93261_idx')],
            },
        ),
    ]
