# Generated by Django 5.2.3 on 2025-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_conta', models.CharField(max_length=255)),
                ('ip_da_integracao', models.CharField(max_length=255)),
                ('tolerancia_tempo_sem_resposta', models.IntegerField()),
                ('tolerancia_de_envio_de_comandos', models.IntegerField()),
                ('quantidade_de_erros_simuntaneos', models.IntegerField()),
                ('tempo_aguardar_retorno', models.IntegerField()),
                ('tecnologia', models.CharField(choices=[('ônix', 'ônix'), ('omnilink', 'omnilink'), ('sascar', 'sascar'), ('autotrack', 'autotrack'), ('siga', 'siga')], max_length=255)),
                ('caminho_aplicacao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=255)),
                ('inicio_horario_tolerancia', models.TimeField()),
                ('fim_horario_tolerancia', models.TimeField()),
                ('empresa_contato', models.CharField(max_length=255)),
                ('monitorado_guardiao', models.BooleanField(default=False)),
                ('ignorado_monitor_integracoes', models.BooleanField(default=False)),
                ('enviar_comandos', models.BooleanField(default=False)),
            ],
        ),
    ]
