# Generated by Django 5.2.5 on 2025-08-28 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7, verbose_name='Status')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('documento', models.CharField(help_text='Somente números.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{11}|\\d{14})$', 'Informe 11 (CPF) ou 14 (CNPJ) dígitos.')], verbose_name='Documento')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embarcador',
                'verbose_name_plural': 'Embarcadores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='embarcador__nome_3aec6e_idx'), models.Index(fields=['documento'], name='embarcador__documen_676a80_idx'), models.Index(fields=['status'], name='embarcador__status_43101d_idx')],
            },
        ),
    ]
