# Generated by Django 5.2.5 on 2025-09-02 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{7}$', 'Informe 7 caracteres (placa).')])),
                ('modelo', models.CharField(max_length=60)),
                ('ano_fabricacao', models.CharField(max_length=4, verbose_name='Ano de fabricação')),
                ('ano_modelo', models.CharField(max_length=4, verbose_name='Ano do modelo')),
                ('cor', models.CharField(max_length=30)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=25)),
                ('crlv', models.CharField(max_length=40, verbose_name='CRLV')),
                ('telefone_veiculo', models.CharField(blank=True, max_length=20, verbose_name='Telefone do veículo')),
                ('cidade_emplacamento', models.CharField(max_length=100, verbose_name='Cidade do emplacamento')),
                ('frota', models.CharField(blank=True, max_length=30)),
                ('proprietario', models.CharField(max_length=100)),
                ('fator_rpm', models.CharField(blank=True, max_length=20, verbose_name='Fator de RPM')),
                ('fator_velocidade', models.CharField(blank=True, max_length=20, verbose_name='Fator de velocidade')),
                ('numero_eixos', models.PositiveIntegerField()),
                ('tipo_suspensao', models.CharField(choices=[('AR', 'AR'), ('HIDR', 'Hidropneumática'), ('MECA', 'Mecânica'), ('ROSC', 'Rosca')], default='MECA', max_length=4)),
                ('blindado', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3)),
                ('tipo_equipamento', models.CharField(blank=True, max_length=60)),
                ('tecnologia_rastreador', models.CharField(blank=True, max_length=60)),
                ('rastreador', models.CharField(blank=True, max_length=60)),
                ('antt', models.CharField(blank=True, max_length=30, verbose_name='ANTT')),
                ('validade_antt', models.CharField(blank=True, max_length=30, verbose_name='Validade ANTT')),
                ('rntrc', models.CharField(blank=True, max_length=30, verbose_name='RNTRC')),
                ('validade_rntrc', models.DateField(blank=True, null=True, verbose_name='Validade RNTRC')),
                ('capacidade_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade (kg)')),
                ('tara_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tara (kg)')),
                ('cubagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('foto_crlv', models.FileField(blank=True, null=True, upload_to='trucks/crlv/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='truck_truck_placa_3f3efd_idx'), models.Index(fields=['status'], name='truck_truck_status_e679f9_idx')],
            },
        ),
    ]
