# Generated by Django 5.2.5 on 2025-08-28 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('status_associacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7, verbose_name='Status da associação')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{7}$', 'Informe 7 caracteres (placa).')])),
                ('ano_fabricacao', models.CharField(max_length=4, verbose_name='Ano de fabricação')),
                ('ano_modelo', models.CharField(max_length=4, verbose_name='Ano do modelo')),
                ('cor', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=60)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=25)),
                ('crlv', models.CharField(max_length=40, verbose_name='CRLV')),
                ('telefone_veiculo', models.CharField(blank=True, max_length=20, verbose_name='Telefone do veículo')),
                ('data_validade_licenciamento', models.DateField(verbose_name='Data de validade do licenciamento')),
                ('frota', models.CharField(blank=True, max_length=30)),
                ('gr_golden', models.CharField(blank=True, max_length=30, verbose_name='GR GOLDEN')),
                ('senha_veiculo', models.CharField(blank=True, max_length=30)),
                ('senha_coacao', models.CharField(blank=True, max_length=30, verbose_name='Senha de coação')),
                ('proprietario', models.CharField(max_length=100)),
                ('cidade_emplacamento', models.CharField(max_length=100, verbose_name='Cidade do emplacamento')),
                ('fator_rpm', models.CharField(blank=True, max_length=20, verbose_name='Fator de RPM')),
                ('fator_velocidade', models.CharField(blank=True, max_length=20, verbose_name='Fator de velocidade')),
                ('numero_eixos', models.CharField(max_length=10, verbose_name='Número de eixos')),
                ('status_carga', models.CharField(choices=[('CARREGADO', 'Carregado'), ('DESCARREGADO', 'Descarregado')], default='DESCARREGADO', max_length=15)),
                ('unidade_medida', models.CharField(choices=[('FARDO', 'Fardo'), ('LITRO', 'Litro'), ('QUILOGRAMA', 'Quilograma'), ('PALLET', 'Pallet'), ('METRO_CUBICO', 'Metro cúbico')], default='QUILOGRAMA', max_length=15)),
                ('numero_pallets', models.CharField(blank=True, max_length=10, verbose_name='Número de pallets')),
                ('pgr_minimo', models.CharField(blank=True, max_length=30, verbose_name='PGR Mínimo')),
                ('tecnologia_rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('tipo_carroceria', models.CharField(blank=True, max_length=60)),
                ('tecnologia_rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('sigla_base', models.CharField(blank=True, max_length=20)),
                ('bases_operacionais', models.CharField(blank=True, max_length=200)),
                ('antt', models.CharField(blank=True, max_length=30, verbose_name='ANTT')),
                ('validade_antt', models.CharField(blank=True, max_length=30, verbose_name='Validade ANTT')),
                ('rntrc', models.CharField(blank=True, max_length=30, verbose_name='RNTRC')),
                ('validade_rntrc', models.DateField(blank=True, null=True, verbose_name='Validade RNTRC')),
                ('tac', models.CharField(blank=True, max_length=30, verbose_name='TAC')),
                ('validade_tac', models.DateField(blank=True, null=True, verbose_name='Validade TAC')),
                ('tara_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tara (kg)')),
                ('cubagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidade_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade (kg)')),
                ('quarteirizando', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('velocidade_alto_desempenho', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3, verbose_name='Velocidade de alto desempenho')),
                ('blindado', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('suspensao', models.CharField(choices=[('AR', 'AR'), ('HIDR', 'Hidropneumática'), ('MECA', 'Mecânica'), ('ROSC', 'Rosca')], default='MECA', max_length=4)),
                ('tipo_equipamento', models.CharField(blank=True, max_length=60)),
                ('observacao', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('foto_crlv', models.FileField(blank=True, null=True, upload_to='carretas/crlv/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carreta',
                'verbose_name_plural': 'Carretas',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='carreta_car_placa_276b85_idx'), models.Index(fields=['status'], name='carreta_car_status_0112a6_idx'), models.Index(fields=['status_associacao'], name='carreta_car_status__5e3747_idx')],
            },
        ),
    ]
