# Generated by Django 5.2.5 on 2025-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, unique=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Operacional',
                'verbose_name_plural': 'Status Operacionais',
                'ordering': ['descricao'],
                'indexes': [models.Index(fields=['descricao'], name='status_oper_descric_46a6bd_idx')],
            },
        ),
    ]
