# Generated by Django 5.2.5 on 2025-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('Tipo_de_motivo', models.CharField(choices=[('Embarque cancelado', 'Embarque cancelado'), ('Veiculo com problemas', 'Veiculo com problemas'), ('Rastreador com problemas', 'Rastreador com problemas'), ('Mercadoria com problemas', 'Mercadoria com problemas'), ('Motorista não autorizado', 'Motorista não autorizado'), ('Nota fiscal pendente', 'Nota fiscal pendente'), ('Outros', 'Outros'), ('Checklist não aprovado', 'Checklist não aprovado'), ('Alteração de status para multiplas viagens', 'Alteração de status para multiplas viagens'), ('Roteiro de atividades prioritário', 'Roteiro de atividades prioritário'), ('Alteração de status para multiplas viagens', 'Alteração de status para multiplas viagens'), ('Roteiro de atividades prioritário', 'Roteiro de atividades prioritário'), ('Causa de sinistro', 'Causa de sinistro')], max_length=50)),
                ('Status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50)),
            ],
        ),
    ]
