# Generated by Django 5.2.3 on 2025-08-22 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_motivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrodemotivo',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Cadastro de Motivo', 'verbose_name_plural': 'Cadastros de Motivos'},
        ),
        migrations.AddField(
            model_name='cadastrodemotivo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='cadastrodemotivo',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cadastrodemotivo',
            name='Status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cadastrodemotivo',
            name='Tipo_de_motivo',
            field=models.CharField(choices=[('Embarque cancelado', 'Embarque cancelado'), ('Veiculo com problemas', 'Veiculo com problemas'), ('Rastreador com problemas', 'Rastreador com problemas'), ('Mercadoria com problemas', 'Mercadoria com problemas'), ('Motorista não autorizado', 'Motorista não autorizado'), ('Nota fiscal pendente', 'Nota fiscal pendente'), ('Outros', 'Outros'), ('Checklist não aprovado', 'Checklist não aprovado'), ('Alteração de status para multiplas viagens', 'Alteração de status para multiplas viagens'), ('Roteiro de atividades prioritário', 'Roteiro de atividades prioritário'), ('Causa de sinistro', 'Causa de sinistro')], max_length=50, verbose_name='Tipo de Motivo'),
        ),
        migrations.AlterField(
            model_name='cadastrodemotivo',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
    ]
