# Generated by Django 5.2.5 on 2025-09-01 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=120, verbose_name='Rastreador')),
                ('id_dispositivo', models.CharField(help_text='Identificador único do equipamento na tecnologia.', max_length=100, unique=True, verbose_name='ID do dispositivo')),
                ('versao_tecnologia', models.CharField(blank=True, max_length=120, verbose_name='Versão da tecnologia')),
                ('conta_tecnologia', models.CharField(blank=True, help_text='Ex.: TELEMONITORADOS', max_length=120, verbose_name='Conta de tecnologia')),
                ('grupo_comandos', models.CharField(blank=True, help_text='Seleção do grupo de comandos aplicável.', max_length=120, verbose_name='Grupo de comandos')),
                ('tempo_satelital_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Satelital (min)')),
                ('tempo_gprs_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo GPRS (min)')),
                ('tempo_medio_posicionamento_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo médio de posicionamento (min)')),
                ('fator_velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fator de velocidade')),
                ('faixa_temperatura', models.CharField(blank=True, choices=[('TESTE', 'Teste'), ('FAIXA_TESTE', 'Faixa Teste')], max_length=20, verbose_name='Faixa de temperatura')),
                ('status_rastreador', models.CharField(choices=[('DESABILITADO', 'Desabilitado para sinal/espelhamento'), ('ESP_RASTREANDO', 'Espelhado com rastreamento'), ('ESP_SEM_RASTREIO', 'Espelhado sem rastreamento'), ('NORMAL', 'Normal'), ('TRANSFERIDO', 'Transferido')], db_index=True, default='NORMAL', max_length=20, verbose_name='Status do rastreador')),
                ('ativo_ws', models.BooleanField(default=False, verbose_name='Ativo WS')),
                ('ativo_gestao_risco', models.BooleanField(default=False, verbose_name='Ativo para gerenciamento de risco')),
                ('lista_branca_autotrac_ade', models.BooleanField(default=False, verbose_name='Lista branca do Autotrac ADE')),
                ('inteligencia_embarcada', models.BooleanField(default=False, verbose_name='Possui inteligência embarcada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rastreador',
                'verbose_name_plural': 'Rastreadores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='cadastro_ra_nome_76aec2_idx'), models.Index(fields=['id_dispositivo'], name='cadastro_ra_id_disp_9f4d0b_idx'), models.Index(fields=['status_rastreador'], name='cadastro_ra_status__b01205_idx')],
            },
        ),
    ]
