# Generated by Django 5.2.5 on 2025-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrotecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('versao', models.CharField(max_length=50)),
                ('tempo_satelital', models.IntegerField()),
                ('tempo_gprs', models.IntegerField()),
                ('homologado_para_risco', models.BooleanField(default=False)),
                ('homologado_para_logistica', models.BooleanField(default=False)),
                ('permitir_mensagem_livre', models.BooleanField(default=False)),
                ('tipo_de_comunicacao', models.CharField(max_length=250)),
                ('posicoes_calculo_posicionamento', models.IntegerField()),
                ('comunicacao', models.CharField(choices=[('Satelital', 'Satelital'), ('Hibrido', 'Hibrido'), ('Grupo GPRS', 'Grupo GPRS'), ('Prime', 'Prime'), ('LBS', 'LBS')], max_length=50)),
            ],
        ),
    ]
