# Generated by Django 5.2.3 on 2025-08-25 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versao_da_tecnologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrotecnologia',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Versão da Tecnologia', 'verbose_name_plural': 'Versões da Tecnologia'},
        ),
        migrations.AddField(
            model_name='cadastrotecnologia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='cadastrotecnologia',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='comunicacao',
            field=models.CharField(choices=[('Satelital', 'Satelital'), ('Hibrido', 'Hibrido'), ('Grupo GPRS', 'Grupo GPRS'), ('Prime', 'Prime'), ('LBS', 'LBS')], max_length=50, verbose_name='Comunicação'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='homologado_para_logistica',
            field=models.BooleanField(default=False, verbose_name='Homologado para Logística'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='homologado_para_risco',
            field=models.BooleanField(default=False, verbose_name='Homologado para Risco'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='permitir_mensagem_livre',
            field=models.BooleanField(default=False, verbose_name='Permitir Mensagem Livre'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='posicoes_calculo_posicionamento',
            field=models.IntegerField(verbose_name='Posições Cálculo Posicionamento'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='tempo_gprs',
            field=models.IntegerField(verbose_name='Tempo GPRS'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='tempo_satelital',
            field=models.IntegerField(verbose_name='Tempo Satelital'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='tipo_de_comunicacao',
            field=models.CharField(max_length=250, verbose_name='Tipo de Comunicação'),
        ),
        migrations.AlterField(
            model_name='cadastrotecnologia',
            name='versao',
            field=models.CharField(max_length=50, verbose_name='Versão'),
        ),
    ]
