# Generated by Django 5.2.5 on 2025-08-28 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], db_index=True, default='ATIVO', max_length=7)),
                ('status_associacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], db_index=True, default='ATIVO', max_length=7, verbose_name='Status da associação')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano_fabricacao', models.CharField(max_length=4)),
                ('ano_modelo', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=60)),
                ('renavam', models.CharField(blank=True, max_length=20)),
                ('chassi', models.CharField(blank=True, max_length=25)),
                ('crlv', models.CharField(blank=True, max_length=50, verbose_name='CRLV')),
                ('telefone_veiculo', models.CharField(blank=True, max_length=20)),
                ('validade_licenciamento', models.DateField(blank=True, null=True)),
                ('frota', models.CharField(blank=True, max_length=30)),
                ('proprietario_documento', models.CharField(blank=True, max_length=30)),
                ('senha_veiculo', models.CharField(blank=True, max_length=30)),
                ('senha_coacao', models.CharField(blank=True, max_length=30)),
                ('proprietario', models.CharField(blank=True, max_length=100)),
                ('cidade_emplacamento', models.CharField(blank=True, max_length=60)),
                ('estacao_rastreamento_operador', models.CharField(blank=True, max_length=60)),
                ('estacao_rastreamento_supervisor', models.CharField(blank=True, max_length=60)),
                ('gestor_frota', models.CharField(blank=True, max_length=60)),
                ('fator_rpm', models.CharField(blank=True, max_length=20)),
                ('fator_velocidade', models.CharField(blank=True, max_length=20)),
                ('numero_eixos', models.CharField(blank=True, max_length=10)),
                ('pgr_minimo', models.CharField(blank=True, max_length=30, verbose_name='PGR MÍNIMO')),
                ('tecnologia_rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('tipo_operacao', models.CharField(blank=True, max_length=60, verbose_name='Tipo de operação')),
                ('rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('tecnologia_rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('sigla_base', models.CharField(blank=True, max_length=20)),
                ('bases_operacionais', models.CharField(blank=True, max_length=120)),
                ('escolta', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], default='NAO', max_length=3)),
                ('antt', models.CharField(blank=True, max_length=30)),
                ('validade_antt', models.DateField(blank=True, null=True)),
                ('rntrc', models.CharField(blank=True, max_length=30)),
                ('validade_rntrc', models.DateField(blank=True, null=True)),
                ('tac', models.CharField(blank=True, max_length=30)),
                ('validade_tac', models.DateField(blank=True, null=True)),
                ('tara_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tara (kg)')),
                ('cubagem_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cubagem (m³)')),
                ('quarteirizando', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], default='NAO', max_length=3)),
                ('veiculo_alto_desempenho', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], default='NAO', max_length=3)),
                ('blindado', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], default='NAO', max_length=3)),
                ('suspensao', models.CharField(blank=True, choices=[('AR', 'AR'), ('HIDR', 'HIDROPNEUMÁTICA'), ('MECA', 'MECÂNICA'), ('ROSC', 'ROSCA')], max_length=4)),
                ('possui_lock', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], default='NAO', max_length=3, verbose_name='Possui LOCK')),
                ('area_util_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área útil (mm)')),
                ('largura_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Largura (mm)')),
                ('altura_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (mm)')),
                ('capacidade_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade (kg)')),
                ('tipo_equipamento', models.CharField(blank=True, max_length=60, verbose_name='Tipo de equipamento')),
                ('tipo_combustivel', models.CharField(blank=True, choices=[('GASOLINA', 'GASOLINA'), ('DIESEL', 'DIESEL'), ('GNV', 'GÁS NATURAL VEICULAR'), ('ETANOL', 'ETANOL')], max_length=12, verbose_name='Tipo de combustível')),
                ('observacao', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('foto_crlv', models.FileField(blank=True, null=True, upload_to='cavalos/crlv/', verbose_name='Foto (CRLV)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cavalo',
                'verbose_name_plural': 'Cavalos',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='cavalo_cava_placa_8fc28f_idx'), models.Index(fields=['status'], name='cavalo_cava_status_8daf0c_idx'), models.Index(fields=['status_associacao'], name='cavalo_cava_status__9f97f6_idx')],
            },
        ),
    ]
