# Generated by Django 5.2.5 on 2025-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaoConformidadeVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('viagem', models.CharField(max_length=100, verbose_name='Viagem')),
                ('veiculo', models.CharField(max_length=50, verbose_name='Veículo')),
                ('frota', models.CharField(max_length=50, verbose_name='Frota')),
                ('suspenso_desde', models.DateField(verbose_name='Suspenso desde')),
                ('situacao', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('DESBLOQUEADO', 'Desbloqueado')], db_index=True, default='BLOQUEADO', max_length=13, verbose_name='Situação')),
                ('agendamento_liberacao', models.DateField(blank=True, null=True, verbose_name='Agendamento de liberação')),
                ('transportador', models.CharField(max_length=150, verbose_name='Transportador')),
                ('problemas_mecanicos', models.CharField(blank=True, max_length=255, verbose_name='Problemas mecânicos')),
                ('problemas_rastreador', models.CharField(blank=True, max_length=255, verbose_name='Problemas de rastreador')),
                ('observacao', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('motivo_interno', models.CharField(blank=True, max_length=255, verbose_name='Motivo interno')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Não Conformidade de Veículo',
                'verbose_name_plural': 'Não Conformidades de Veículo',
                'ordering': ['-suspenso_desde', 'cliente'],
                'indexes': [models.Index(fields=['cliente'], name='nao_conform_cliente_fbd0e9_idx'), models.Index(fields=['veiculo'], name='nao_conform_veiculo_5c957c_idx'), models.Index(fields=['situacao'], name='nao_conform_situaca_1be895_idx')],
            },
        ),
    ]
