# Generated by Django 5.2.5 on 2025-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True, verbose_name='Descrição')),
                ('tipo_carroceria', models.CharField(max_length=120, verbose_name='Tipo de carroceria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de segmento',
                'verbose_name_plural': 'Tipos de segmento',
                'ordering': ['descricao'],
                'indexes': [models.Index(fields=['descricao'], name='tipo_segmen_descric_bc7b6c_idx'), models.Index(fields=['tipo_carroceria'], name='tipo_segmen_tipo_ca_b147f2_idx')],
            },
        ),
    ]
