# Generated by Django 5.2.5 on 2025-08-29 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('status_associacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano_fabricacao', models.CharField(max_length=4)),
                ('ano_modelo', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=60)),
                ('renavam', models.CharField(blank=True, max_length=20)),
                ('chassi', models.CharField(blank=True, max_length=30)),
                ('crlv', models.CharField(blank=True, max_length=30)),
                ('telefone_veiculo', models.CharField(blank=True, max_length=20)),
                ('validade_licenciamento', models.DateField(blank=True, null=True)),
                ('frota', models.CharField(blank=True, max_length=30)),
                ('proprietario_documento', models.CharField(blank=True, max_length=30)),
                ('senha_veiculo', models.CharField(blank=True, max_length=30)),
                ('senha_coacao', models.CharField(blank=True, max_length=30)),
                ('proprietario_posse', models.CharField(blank=True, max_length=60)),
                ('cidade_emplacamento', models.CharField(blank=True, max_length=60)),
                ('estacao_rastreamento_operador', models.CharField(blank=True, max_length=60)),
                ('estacao_rastreamento_supervisor', models.CharField(blank=True, max_length=60)),
                ('gestor_frota', models.CharField(blank=True, max_length=60)),
                ('pgr_minimo', models.CharField(blank=True, max_length=30)),
                ('tecnologia_rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('rastreador_principal', models.CharField(blank=True, max_length=60)),
                ('tipo_operacao', models.CharField(blank=True, max_length=60)),
                ('rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('tecnologia_rastreador_secundario', models.CharField(blank=True, max_length=60)),
                ('sigla_base', models.CharField(blank=True, max_length=20)),
                ('bases_operacionais', models.CharField(blank=True, max_length=120)),
                ('escolta', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('antt', models.CharField(blank=True, max_length=30)),
                ('validade_antt', models.DateField(blank=True, null=True)),
                ('rntrc', models.CharField(blank=True, max_length=30)),
                ('validade_rntrc', models.DateField(blank=True, null=True)),
                ('tac', models.CharField(blank=True, max_length=30)),
                ('validade_tac', models.DateField(blank=True, null=True)),
                ('tara_kg', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tara (kg)')),
                ('cubagem', models.CharField(blank=True, max_length=30)),
                ('quarteirizando', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('veiculo_alto_desempenho', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('blindado', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('suspensao', models.CharField(blank=True, choices=[('AR', 'AR'), ('HIDR', 'Hidropneumática'), ('MECA', 'Mecânica'), ('ROSC', 'Rosca')], max_length=4)),
                ('possui_lock', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], default='NAO', max_length=3)),
                ('area_util_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('largura_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_mm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacidade_kg', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_equipamento', models.CharField(blank=True, max_length=60)),
                ('tipo_combustivel', models.CharField(blank=True, choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('GNV', 'Gás Natural Veicular'), ('ETANOL', 'Etanol')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('foto_crlv', models.FileField(blank=True, null=True, upload_to='motos/crlv/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='moto_moto_placa_93a7d9_idx'), models.Index(fields=['status'], name='moto_moto_status_ec9049_idx'), models.Index(fields=['status_associacao'], name='moto_moto_status__f31607_idx')],
            },
        ),
    ]
